from sympy import (symbols, Symbol, Matrix, eye, sqrt, Abs, ask, Q, refine, simplify, solveset, S,
                   Interval, Poly, factor, GF, ZZ, QQ, I, re, im, conjugate, floor, sign, log, exp)
import mpmath
x, y = symbols("x y")
p = Symbol("p", positive=True)
r = Symbol("r", real=True)
k = Symbol("k", integer=True)
A = Matrix([[2, 1], [1, 3]])
B = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print("det:", B.det())
print("inv:", B.inv())
print("eigen:", A.eigenvals())
print("charpoly:", A.charpoly(x).as_expr())
print("rref:", Matrix([[1, 2, 3], [2, 4, 6], [1, 0, 1]]).rref())
print("nullspace:", Matrix([[1, 2, 3], [2, 4, 6]]).nullspace())
print("matpow:", (Matrix([[1, 1], [1, 0]]) ** 30)[0, 1])
print("symbolic_det:", Matrix([[x, y], [y, x]]).det().factor())
print("solve_lin:", B.LUsolve(Matrix([1, 2, 3])).T)
print("eye_trace:", (eye(4) * 3).trace())
print("sqrt_pos:", sqrt(p ** 2), "sqrt_gen:", sqrt(x ** 2))
print("abs_real:", Abs(r) ** 2, "abs_pos:", Abs(p))
print("ask_pos:", ask(Q.positive(p + 1)), ask(Q.positive(r)), ask(Q.even(2 * k)))
print("refine:", refine(sqrt(x ** 2), Q.negative(x)))
print("cos_int:", simplify((-1) ** (2 * k)), floor(k), sign(p))
print("log_pos:", log(exp(r)), log(exp(x)))
print("re_im:", re(r + 2 * I), im(x), conjugate(r))
print("dom_interval:", solveset(x ** 2 - 4 < 0, x, domain=S.Reals))
print("dom_ints:", solveset(x ** 2 - 2, x, domain=S.Integers))
print("dom_interval2:", solveset(x - 3, x, domain=Interval(0, 2)))
print("poly_ZZ:", Poly(x ** 2 + 2 * x + 1, x, domain=ZZ).factor_list())
print("poly_QQ:", Poly(x ** 2 / 2 + 1, x).domain, Poly(x ** 2 + 1, x, domain=QQ).domain)
print("factor_mod:", factor(x ** 4 + 1, modulus=2))
print("gf:", GF(7)(3) * GF(7)(5))
mpmath.mp.dps = 50
print("mp_pi:", mpmath.pi)
print("mp_quad:", mpmath.quad(lambda t: mpmath.exp(-t * t), [-mpmath.inf, mpmath.inf]))
print("mp_zeta:", mpmath.zeta(3))
