from sympy import (symbols, simplify, expand, factor, cancel, apart, together, trigsimp,
                   sin, cos, exp, log, sqrt, Rational, nsimplify, pi, I, expand_trig, radsimp, gcd, Poly)
x, y, z = symbols("x y z")
print("expand_cube:", expand((x + y) ** 3))
print("expand_mixed:", expand((x - 2 * y + 1) * (x + y) ** 2))
print("factor_diff4:", factor(x ** 4 - y ** 4))
print("factor_poly:", factor(x ** 3 - 6 * x ** 2 + 11 * x - 6))
print("factor_gauss:", factor(x ** 2 + 1, extension=I))
print("factor_sqrt2:", factor(x ** 2 - 2, extension=sqrt(2)))
print("simplify_trig:", simplify(sin(x) ** 2 + cos(x) ** 2))
print("simplify_rat:", simplify((x ** 2 - 1) / (x - 1)))
print("simplify_exp:", simplify(exp(x) * exp(y) / exp(x + y - 1)))
print("trigsimp:", trigsimp(2 * sin(x) * cos(x)))
print("expand_trig:", expand_trig(sin(2 * x + y)))
print("cancel:", cancel((x ** 3 - 1) / (x ** 2 - 1)))
print("apart:", apart(1 / (x * (x + 1) * (x + 2)), x))
print("together:", together(1 / x + 1 / y))
print("radsimp:", radsimp(1 / (1 + sqrt(2))))
print("rational:", Rational(1, 3) + Rational(1, 6) - Rational(2, 7))
print("nsimplify:", nsimplify(0.125), nsimplify(1.4142135623730951, [sqrt(2)]))
print("gcd:", gcd(x ** 2 - 1, x ** 2 - 2 * x + 1))
print("poly_div:", Poly(x ** 3 + 2 * x + 1, x).div(Poly(x - 1, x)))
print("log_expand:", expand(log(x * y), force=True))
print("pi_digits:", pi.evalf(40))
