from sympy import (symbols, diff, integrate, limit, series, solve, solveset, linsolve, roots, dsolve,
                   Function, Eq, sin, cos, exp, log, sqrt, oo, S, Rational, summation, factorial)
x, y, n = symbols("x y n")
f = Function("f")
print("diff_prod:", diff(sin(x) * x ** 3, x))
print("diff_chain:", diff(exp(x ** 2) * log(x), x, 2))
print("diff_partial:", diff(x ** 2 * y ** 3, x, y))
print("int_poly:", integrate(3 * x ** 2 + 2 * x, x))
print("int_def:", integrate(x * exp(-x), (x, 0, oo)))
print("int_gauss:", integrate(exp(-x ** 2), (x, -oo, oo)))
print("int_trig:", integrate(sin(x) ** 2, (x, 0, 2 * 3)))
print("limit_sinc:", limit(sin(x) / x, x, 0))
print("limit_e:", limit((1 + 1 / n) ** n, n, oo))
print("series_exp:", series(exp(x), x, 0, 6))
print("solve_quad:", solve(x ** 2 - 3 * x + 2, x))
print("solve_cubic:", solve(x ** 3 - 2, x))
print("solve_sys:", solve([x + y - 3, x - y - 1], [x, y], dict=True))
print("solveset_real:", solveset(x ** 2 + 1, x, domain=S.Reals))
print("solveset_cplx:", solveset(x ** 2 + 1, x, domain=S.Complexes))
print("solveset_sin:", solveset(sin(x), x, domain=S.Reals))
print("linsolve:", linsolve([x + 2 * y - 5, 3 * x - y - 1], x, y))
print("roots:", roots(x ** 3 - 3 * x ** 2 + 3 * x - 1, x))
print("dsolve:", dsolve(Eq(f(x).diff(x, 2) + f(x), 0), f(x)))
print("sum_squares:", summation(n ** 2, (n, 1, 100)))
print("sum_basel:", summation(1 / n ** 2, (n, 1, oo)))
print("sum_exp:", summation(1 / factorial(n), (n, 0, oo)))
print("rational_int:", integrate(1 / (x ** 2 + 1), (x, 0, 1)))
